# Generated by Django 4.1.3 on 2024-04-10 06:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accomidation',
            fields=[
                ('accomidation_id', models.UUIDField(default=uuid.UUID('f3e290c5-a113-4d98-b2dc-a376cf49916e'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('distance', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('availability', models.IntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('amenity_id', models.UUIDField(default=uuid.UUID('3616fc7d-00fe-467d-91dc-73b0475281fe'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('person_id', models.UUIDField(default=uuid.UUID('5fde7a79-9547-4f36-a26d-32ec24fe5a39'), primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('password', models.CharField(default='password', max_length=225)),
                ('firstname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=False)),
                ('phone_number', models.CharField(default='', max_length=250)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('university_id', models.UUIDField(default=uuid.UUID('da5eb4d3-3625-411d-8863-609303ade017'), primary_key=True, serialize=False)),
                ('university_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=250)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.UUID('27950634-f5df-4fc8-ae91-060d6169c435'), primary_key=True, serialize=False)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('person_id', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='accommodation.person')),
            ],
        ),
        migrations.CreateModel(
            name='AccomidationAmenities',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('e56f7b76-b5ea-4544-80d1-5f0111c0fca2'), primary_key=True, serialize=False)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('accomidation_id', models.ForeignKey(db_column='accomidation_id', on_delete=django.db.models.deletion.CASCADE, to='accommodation.accomidation')),
                ('amenity_id', models.ForeignKey(db_column='amenity_id', on_delete=django.db.models.deletion.CASCADE, to='accommodation.amenities')),
            ],
        ),
    ]
