# Generated by Django 4.1.3 on 2024-04-11 05:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomidation',
            name='person_id',
            field=models.ForeignKey(db_column='person_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='accommodation.person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accomidation',
            name='accomidation_id',
            field=models.UUIDField(default=uuid.UUID('82fbfd32-5a88-44db-a9fb-1f87418e5d3d'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accomidationamenities',
            name='id',
            field=models.UUIDField(default=uuid.UUID('57ed3eb3-e8ce-4033-bc21-3ac45e7c6c21'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='amenity_id',
            field=models.UUIDField(default=uuid.UUID('2a9c0a1f-9cdd-4edf-9a6c-68b4f5d83f8f'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='booking_id',
            field=models.UUIDField(default=uuid.UUID('93bf952e-72f6-46bf-bfaa-33e547b35ba8'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_id',
            field=models.UUIDField(default=uuid.UUID('12cbfdab-5cc8-4e30-89c6-fd20bbf80aa0'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='universities',
            name='university_id',
            field=models.UUIDField(default=uuid.UUID('5171c388-e6de-4b9a-bf2b-02dddec45251'), primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='UniversitiesDistances',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('fa68eaaa-4e50-4eed-b771-aa03c4e12457'), primary_key=True, serialize=False)),
                ('distance', models.CharField(max_length=255)),
                ('accomidation_id', models.ForeignKey(db_column='accomidation_id', on_delete=django.db.models.deletion.CASCADE, to='accommodation.accomidation')),
                ('university_id', models.ForeignKey(db_column='university_id', on_delete=django.db.models.deletion.CASCADE, to='accommodation.universities')),
            ],
        ),
    ]
