# Generated by Django 4.1.3 on 2024-04-12 16:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_accomidation_person_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomidation',
            name='distance',
        ),
        migrations.AlterField(
            model_name='accomidation',
            name='accomidation_id',
            field=models.UUIDField(default=uuid.UUID('8e6ef699-fbcd-42d7-b442-f5aac1cd4ba7'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accomidationamenities',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e324bfa3-f1c2-4181-81d6-838884dccfb1'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='amenity_id',
            field=models.UUIDField(default=uuid.UUID('b2d09756-3a68-4b34-ba81-d2e7c1283838'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='booking_id',
            field=models.UUIDField(default=uuid.UUID('c4aa46d2-292a-4e34-8460-227ff0a5c83b'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_id',
            field=models.UUIDField(default=uuid.UUID('88216765-507f-4395-8e10-61fb838185d7'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='universities',
            name='university_id',
            field=models.UUIDField(default=uuid.UUID('a149241b-937f-4612-b164-20dc66d4af7b'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='universitiesdistances',
            name='id',
            field=models.UUIDField(default=uuid.UUID('941d17e6-5e53-4572-97fe-b3a92b2068f6'), primary_key=True, serialize=False),
        ),
    ]
