# Generated by Django 4.1.3 on 2024-04-21 05:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0003_remove_accomidation_distance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='furnitured',
            fields=[
                ('furnitured_id', models.UUIDField(default=uuid.UUID('336d69ba-5489-40b2-ace5-31e464a096fe'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='accomidation',
            name='accomidation_id',
            field=models.UUIDField(default=uuid.UUID('edcb475c-751c-4081-b393-542ed216146c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accomidationamenities',
            name='id',
            field=models.UUIDField(default=uuid.UUID('06dd2aae-2f3a-4446-821f-2a5b9a227e24'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='amenity_id',
            field=models.UUIDField(default=uuid.UUID('1d860cdb-04c3-444a-8920-f9433a7e966d'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='booking_id',
            field=models.UUIDField(default=uuid.UUID('ba20f734-700b-46d9-99e5-abcb72b3b3ef'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_id',
            field=models.UUIDField(default=uuid.UUID('1577bf70-81ef-4fc5-b009-acc6925680ee'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='universities',
            name='university_id',
            field=models.UUIDField(default=uuid.UUID('af703451-a681-4683-b9e2-95b8f0f9b08f'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='universitiesdistances',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e6d36392-8213-4527-9738-d848942612f7'), primary_key=True, serialize=False),
        ),
    ]
