# Generated by Django 4.1.3 on 2024-04-21 06:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0004_furnitured_alter_accomidation_accomidation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomidation',
            name='furnituredname',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accomidation',
            name='accomidation_id',
            field=models.UUIDField(default=uuid.UUID('4b47fa56-7c55-46b3-8fe9-70180ebdfb6f'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accomidationamenities',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2818608e-732e-414d-b89d-fa6a7e674e0d'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='amenity_id',
            field=models.UUIDField(default=uuid.UUID('20ba06d4-596f-4a34-bad7-9e0308e8f49d'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='booking_id',
            field=models.UUIDField(default=uuid.UUID('0b072a51-d5b9-4a87-afa3-9dcc3ee37dc3'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='furnitured',
            name='furnitured_id',
            field=models.UUIDField(default=uuid.UUID('97d853fb-a2f3-42ed-824f-9c6ed711b225'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_id',
            field=models.UUIDField(default=uuid.UUID('543321c7-7315-4e0a-9056-451522b442c9'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='universities',
            name='university_id',
            field=models.UUIDField(default=uuid.UUID('6ce3ed34-0039-4aec-aca9-5c5236ce6086'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='universitiesdistances',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0b02e846-fbe0-481b-b701-7a3203c368e4'), primary_key=True, serialize=False),
        ),
    ]
